import Head from 'next/head'
import { FC } from 'react'

import { Box } from '@mui/material'

import AppRoot from '../layout/AppRoot'
import SearchField from './SearchField'
import SearchResult from './SearchResult'

import { Props } from '../../types/type'

const Presenter: FC<Props> = ({
  onSearchSubmit,
  control,
  errors,
  searchDetailOpen,
  setSearchDetailOpen,
  valuetext,
  isPriceInValid,
  selectItem,
  isValid,
  result,
  sortItems,
  getValues,
  searchResultCount,
}: Props) => {
  return (
    <>
      <Head>
        <title>Search Practice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppRoot>
        <Box>
          <SearchField
            onSearchSubmit={onSearchSubmit}
            control={control}
            errors={errors}
            searchDetailOpen={searchDetailOpen}
            setSearchDetailOpen={setSearchDetailOpen}
            valuetext={valuetext}
            isPriceInValid={isPriceInValid}
            selectItem={selectItem}
            isValid={isValid}
            result={result}
            sortItems={sortItems}
            getValues={getValues}
          />
        </Box>
        <Box className="mt-3 flex justify-end">{searchResultCount()}</Box>
        <Box className="relative my-3 flex-grow">
          <Box className="w-full overflow-hidden">
            <SearchResult result={result} />
          </Box>
        </Box>
      </AppRoot>
    </>
  )
}
export default Presenter
